### ISSUE TITLE
Wiser Filter located at top of dashboard gets cut off at top

### ISSUE THREAD

**Issue by wohljeff** [WiserSolutions/WiserFilterWidget#1]
Hi there - really excited to use the Wiser Filter but I have to increase the height of my widget in order to get the full dialog to display when it is positioned at the top of the dashboard.  I am using v0.3.0

Thanks, Jeff
![screen shot 2019-02-27 at 5 28 39 pm](https://user-images.githubusercontent.com/11862354/53527644-88cae280-3ab5-11e9-91b0-0e2db17415ec.png)

**Comment by rajiv-mobee** [comment]
Hello Jeff,

This issue was actually resolved a few months ago.  Unfortunately it was not formally included in a release until just now.  Please refer to the latest version (0.4.0) to have this issue resolved.

**Comment by wohljeff** [comment]
Tested and verified - Thank You!
